//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.TravelingDrivers = new HashSet<TravelingDriver>();
        }
    
        public int Id { get; set; }
        public string Identity { get; set; }
        public int NumberOfSeats { get; set; }
        public string CarDescription { get; set; }
        public string AccountNumber { get; set; }
        public string BankNum { get; set; }
        public string BranchNum { get; set; }
        public string OwnerName { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelingDriver> TravelingDrivers { get; set; }
    }
}
