//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationDateRange
    {
        public int Id { get; set; }
        public System.DateTime DateInRange { get; set; }
        public bool IsActive { get; set; }
        public int NumPassengers { get; set; }
        public int NumComplainants { get; set; }
        public bool IsComplain { get; set; }
    
        public virtual Registeration Registeration { get; set; }
    }
}
