//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelingPassenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelingPassenger()
        {
            this.TravelPassengerRanges = new HashSet<TravelPassengerRange>();
            this.Registerations = new HashSet<Registeration>();
        }
    
        public int TravelingIdPassenger { get; set; }
        public int PassengerId { get; set; }
        public string Weekday { get; set; }
        public string Places { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public double Price { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public bool IsEmbedded { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelPassengerRange> TravelPassengerRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registeration> Registerations { get; set; }
    }
}
