//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelReporting
    {
        public int IdTravelingDriver { get; set; }
        public System.DateTime Date { get; set; }
        public int NumPassengers { get; set; }
        public int NumComplainants { get; set; }
        public bool IsPay { get; set; }
    
        public virtual TravelingDriver TravelingDriver { get; set; }
    }
}
